;;; テキトーなキーマップに vi っぽいキーバインドにするよ
;;; 競合するものがあると M-* に置き換えるよ

(defun rc-vise-km (keymap &optional prefix)
  (let* ((prefix (or prefix (kbd "C-c")))
         (premap (or (lookup-key keymap prefix)
                     (let ((km (make-sparse-keymap)))
                       (define-key keymap prefix km)
                       km))))
    (mapcar (lambda (spec)
              (let* ((key  (car spec))
                     (cmd  (cdr spec))
                     (orig (lookup-key keymap key)))
                (define-key keymap key cmd)
                (when orig (define-key premap key orig))
                ))
            `(([?h] . backward-char)
              ([?j] . next-line)
              ([?k] . previous-line)
              ([?l] . forward-char)))))
