(defvar my-dired-clipboard ())
(defun my-dired-do-copy (&optional arg)
  (interactive)
  (let ((files (dired-get-marked-files)))
    (setq my-dired-clipboard (cons (current-buffer) files))
    (message (format "Copied %d files into clipboard." (length files)))))
(defun my-dired-do-paste ()
  (interactive)
  )
(define-key dired-mode-map (kbd "C-c C-c") 'my-dired-do-copy)
